services:
  # Python Flask Web Service (serves both frontend and backend API)
  - type: web
    name: insightiq-project
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --chdir backend app:app
    envVars:
      - key: PORT
        value: 5050
